DROP TABLE relatorio_serv CASCADE;
DROP TABLE relatorio_prod CASCADE;
DROP TABLE relatorio CASCADE;

DROP TABLE equipe_inst_cient_membro CASCADE;
DROP TABLE equipe_inst_cient CASCADE;
DROP TABLE inst_cient CASCADE;

DROP TABLE reg_leg CASCADE;

DROP TYPE REG_LEG_TIPO CASCADE;
DROP TYPE REG_LEG_CATEGORIA CASCADE;

DROP TABLE prod_ncm CASCADE;
DROP TABLE serv_nbs CASCADE;

DROP TABLE hist_co2 CASCADE;
DROP TABLE contrib_co2 CASCADE;
DROP TABLE vinc_contrib_co2 CASCADE;

DROP TABLE acao_co2 CASCADE;
DROP TABLE organiz_socioamb CASCADE;

DROP TABLE filial CASCADE;
DROP TABLE empresa CASCADE;

DROP TABLE org_adm_mun CASCADE;
DROP TABLE uf CASCADE;
DROP TABLE ent_fed CASCADE;

DROP TYPE ENT_FED_TIPO CASCADE;

DROP TYPE CNPJ_TIPO CASCADE;
DROP TYPE CNPJ_RAIZ_TIPO CASCADE;
DROP TYPE CNPJ_ORDEM_TIPO CASCADE;

DROP TYPE CEP_TIPO CASCADE;
